### ISSUE TITLE
`simplexify(::Quadrangle{3,T})` reorders points in resulting `SimpleMesh` when `T` is `Point3f`

### ISSUE THREAD

**Issue by pbouffard** [JuliaGeometry/Meshes.jl#499] opened 2023-07-07 19:38 UTC
MWE:

```
P1 = Point3(0, 1, -1)
P2 = Point3(0, 1, 1)
P3 = Point3(0, -1, 1)
P4 = Point3(0, -1, -1)
quad3 = Quadrangle([P1, P2, P3, P4])
mesh3 = simplexify(quad3)

P1f = Point3f(0, 1, -1)
P2f = Point3f(0, 1, 1)
P3f = Point3f(0, -1, 1)
P4f = Point3f(0, -1, -1)
quad3f = Quadrangle([P1f, P2f, P3f, P4f])
mesh3f = simplexify(quad3f)

@assert vertices(mesh3) == vertices(mesh3f) # fails 
```

In the quad constructed from `Point3` vertices the mesh produced by `simplexify` preserves the order of the vertices, but with `Point3f` the 2nd and 4th vertices are swapped. This results in the triangles having flipped normals.

```
julia> @info "" mesh3 mesh3f
┌ Info:
│   mesh3 =
│    2 SimpleMesh{3,Float64}
│      4 vertices
│        └─Point(0.0, 1.0, -1.0)
│        └─Point(0.0, 1.0, 1.0)
│        └─Point(0.0, -1.0, 1.0)
│        └─Point(0.0, -1.0, -1.0)
│      2 elements
│        └─Triangle(1, 2, 3)
│        └─Triangle(1, 3, 4)
│   mesh3f =
│    2 SimpleMesh{3,Float32}
│      4 vertices
│        └─Point(0.0f0, 1.0f0, -1.0f0)
│        └─Point(0.0f0, -1.0f0, -1.0f0)
│        └─Point(0.0f0, -1.0f0, 1.0f0)
│        └─Point(0.0f0, 1.0f0, 1.0f0)
│      2 elements
│        └─Triangle(1, 2, 3)
└        └─Triangle(1, 3, 4)
```

**Comment by juliohm** [comment] 2023-07-07 20:22
It is funny that in my computer the Float64 case is the one where the vertices are not in the same order.

**Comment by pbouffard** [comment] 2023-07-07 20:26
> It is funny that in my computer the Float64 case is the one where the vertices are not in the same order.

Uh oh, so much for my current workaround which is to just use Float64.  What machine type are you on? Mine is Mac M-series..

**Comment by juliohm** [comment] 2023-07-07 20:34
The problem is in the Polyarea constructor with rings in 3D. It attempts to fix the orientation of the outer ring to be CCW always, but in 3D this doesn't make much sense. I am working on a fix.

**Comment by pbouffard** [comment] 2023-07-07 20:58
Do you know what's causing the odd difference of behavior between our computers? I should have mentioned, I found this in Meshes 0.32.2, but (for me anyway) the behavior doesn't appear on 0.29.

**Comment by juliohm** [comment] 2023-07-07 21:13
I have no idea what may be causing the difference in our machines. I am submitting the fix now, which specializes a path for Ngon geometries to avoid the more general route with PolyArea

**Comment by juliohm** [comment] 2023-07-07 21:30
@pbouffard I am waiting the tests on all supported platforms: https://github.com/JuliaGeometry/Meshes.jl/pull/500

**Comment by pbouffard** [comment] 2023-07-07 21:49
> all supported platforms: #500

Given that (AFAIU) GitHub doesn't have Apple Silicon runners, I guess I probably should run the tests in your PR locally on my machine.

**Comment by juliohm** [comment] 2023-07-07 21:56
Merged the PR, you can try the latest master. I will also trigger a patch release now.

**Closed as completed** 2023-07-07 21:56 UTC
Labels: bug
