### ISSUE TITLE
Plot of CartesianGrid creates undesired intersection between cells

### ISSUE THREAD

**Issue by ErickChacon** [JuliaGeometry/Meshes.jl#711] opened 2024-01-25 08:03 UTC
I have not noticed this behaviour before but it is clear when working with missing values. The plot of a `CartesianGrid` shows some intersection between neighboring cells, while it is not show when the domain is converted to a vector of squares.

```julia
using Meshes
import CairoMakie as MK

d = CartesianGrid(3,3)
n = nelements(d)
v = rand(n)
v[[2, 4, 6, 8]] .= NaN

fig = MK.Figure()
ax1 = MK.Axis(fig[1,1], aspect = MK.DataAspect(), title = "Cartesian grid")
viz!(ax1, d, color = v, colorscheme = :RdBu)
ax2 = MK.Axis(fig[1,2], aspect = MK.DataAspect(), title = "Vector of squares")
viz!(ax2, d[1:n], color = v, colorscheme = :RdBu)
MK.save("makie.pdf", fig)
```

In the figure below, we can see that the cell in the center intersects the other 4 cells when plotting using the method for `CartesianGrid`. In a real application, it creates artifacts in the plot, where the cells do not seem to have the same size.

![2024-01-25-105710_3206x1829_scrot](https://github.com/JuliaGeometry/Meshes.jl/assets/7862458/e4442cba-ff84-4e2b-a618-41829ade63ba)

Im not sure, but seems that this artifact is only clear to see when saving the figure as `pdf`.

**Comment by juliohm** [comment] 2024-01-25 08:43
Thank you Erick for reporting the issue. Can you confirm the issue is
present in the master branch? We changed the recipe to Makie.image recently.

Em qui., 25 de jan. de 2024 05:04, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by ErickChacon** [comment] 2024-01-25 09:21
Yes, the issue also happens when using the current version of master branch.

**Comment by juliohm** [comment] 2024-01-25 09:26
That is probably an issue in the Makie.image and Makie.heatmap then. Can
you try to reduce the MWE to report in Makie.jl instead?

Em qui., 25 de jan. de 2024 06:21, Dr. Erick A. Chacón Montalván <
***@***.***> escreveu:

**Comment by juliohm** [comment] 2024-01-25 14:16
Closing this issue as it seems outside the scope of Meshes.jl

**Closed as completed by juliohm** 2024-01-25 14:16 UTC
Labels: viz
